version: "3.8"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    labels:
      caddy.email: "factsforfriends@gmail.com"
  redirect:
    image: schmunk42/nginx-redirect
    networks:
      - caddy
    environment:
      - SERVER_REDIRECT=news.factsforfriends.de
      - SERVER_REDIRECT_PATH=/launch
      - SERVER_REDIRECT_SCHEME=https
    # optionally define the http code to use for redirection
    # allowed Codes are: 301, 302, 303, 307, 308, default is 301
    #- SERVER_REDIRECT_CODE=301
    # optionally define the http code to redirect POST requests
    # if not set or not in allowed Codes, SERVER_REDIRECT_CODE will be used
    #- SERVER_REDIRECT_POST_CODE=
    # optionally define the http code to redirect PUT, PATCH and DELETE requests
    # if not set or not in allowed Codes, SERVER_REDIRECT_CODE will be used
    #- SERVER_REDIRECT_PUT_PATCH_DELETE_CODE=
    # optionally define the location for the nginx access log
    # if not set /dev/stdout is used
    #- SERVER_ACCESS_LOG=/dev/null
    # optionally define the location for the nginx error log
    # if not set /dev/stderr is used
    #- SERVER_ERROR_LOG=/dev/null
    labels:
      caddy: factsforfriends.de www.factsforfriends.de
      caddy.reverse_proxy: "{{upstreams http 80}}"
  angular:
    image: elangenhan/f3angular:dev
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: dev.factsforfriends.de
      caddy.reverse_proxy: "{{upstreams http 80}}"
  strapi:
    image: strapi/strapi
    restart: unless-stopped
    networks:
      - caddy
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      DATABASE_CLIENT: "${DATABASE_CLIENT}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - ./strapi:/srv/app
    ports:
      - 127.0.0.1:1337:1337
    labels:
      caddy: cms.factsforfriends.de
      caddy.reverse_proxy: "{{upstreams http 1337}}"
  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - caddy
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    env_file:
      - .env
    volumes:
      - ./data/db:/data/db
    ports:
      - 127.0.0.1:27017:27017
networks:
   caddy:
volumes:
  caddy_data: {}