version: "3.8"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    labels:
      caddy.email: "factsforfriends@gmail.com"
  angular:
    image: elangenhan/f3angular:dev
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: factsforfriends.de www.factsforfriends.de
      caddy.reverse_proxy: "{{upstreams http 80}}"
  strapi:
    image: strapi/strapi
    restart: unless-stopped
    networks:
      - caddy
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      DATABASE_CLIENT: "${DATABASE_CLIENT}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - ./strapi:/srv/app
    ports:
      - 127.0.0.1:1337:1337
    labels:
      caddy: cms.factsforfriends.de
      caddy.reverse_proxy: "{{upstreams http 1337}}"
  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - caddy
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    env_file:
      - .env
    volumes:
      - ./data/db:/data/db
    ports:
      - 127.0.0.1:27017:27017
networks:
   caddy:
volumes:
  caddy_data: {}